platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: '2-sdk'

inputs:
  - name: pal-tracker-dotnet

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |
  
    mkdir -p build-output/src/PalTracker
    cp pal-tracker-dotnet/manifest.yml build-output
    
    dotnet test ./pal-tracker-dotnet/test/PalTrackerTests

    dotnet publish ./pal-tracker-dotnet/src/PalTracker --configuration Release \
      --output $(pwd)/build-output/src/PalTracker/bin/Release/netcoreapp2.0/publish
